### ISSUE TITLE
Fails to build when localized contents are added

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#1263]
**Describe the bug**
I'm trying to add l10n content #1262 , however it's failing to build as you can see the error indicated below.

```
> Found duplicate post slug: 'control-focus-with-tabindex' (Error):
    Error: Found duplicate post slug: 'control-focus-with-tabindex'
        at collection.forEach (/home/travis/build/GoogleChrome/web.dev/src/site/_filters/find-by-slug.js:39:13)
        at Array.forEach (<anonymous>)
        at memoize (/home/travis/build/GoogleChrome/web.dev/src/site/_filters/find-by-slug.js:37:14)
        at Object.memoized (/home/travis/build/GoogleChrome/web.dev/.eleventy.js:100:12)
        at TemplateMap.getUserConfigCollection (/home/travis/build/GoogleChrome/web.dev/node_modules/@11ty/eleventy/src/TemplateMap.js:438:47)
        at TemplateMap.initDependencyMap (/home/travis/build/GoogleChrome/web.dev/node_modules/@11ty/eleventy/src/TemplateMap.js:225:54)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
1. Create a language directory like `src/site/content/<lang>`
2. Create a translation mirroring directory architecture of `en`
3. Build

**Expected behavior**
Successfully build (regardless of development server won't be able to serve the localized content) and place localized content.

**Screenshots**
Fails to build as an error message seen above.

**Comment by robdodson** [comment]
hm yeah... I'll have to think about this.
It's failing because I added a function that let's us quickly look up an eleventy post by its slug:
https://github.com/GoogleChrome/web.dev/blob/master/src/site/_filters/find-by-slug.js#L30 but it assumes posts all have unique slugs. I think I'll have to tell it to also consider the language directory.

**Comment by robdodson** [comment]
@agektmr Going to close but feel free to open if this is still happening.
