### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by james-muriithi** [GoogleChrome/web.dev#2040]
Error: Error: Lighthouse returned error: INTERNAL: Extension result empty. Lighthouse calling Page.navigate with https://james-muriithi.github.io/jCheckBox/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5555:13) at http://ghost-rider/devtools_script_api.js:708:9 at Map.forEach (<anonymous>) at chromium.DevTools.Connection.dispatchMessage (http://ghost-rider/devtools_script_api.js:707:76) at chromium.DevTools.Connection.onJsonMessage_ (http://ghost-rider/devtools_script_api.js:689:65) at <anonymous>:1:40

**Comment by robdodson** [comment]
I was able to confirm that both web.dev/measure and running Lighthouse in devtools will time out on this page. Not sure sure. Transferring to the Lighthouse team.
