### ISSUE TITLE
Build process isn't Windows-friendly

### ISSUE THREAD

**Issue by RReverser** [GoogleChrome/web.dev#3672]
**Describe the bug**

It's not possible (or, at least, easy) to contribute to `web.dev` natively on a Windows machine.

**To Reproduce**
1. Clone the repo.
2. Run `npm ci`.
3. Run `npm run dev`.

First error you'll get is

```
> web.dev@2.0.0 dev C:\Users\rreverser\Downloads\web.dev
> npm-run-all clean rollup rollup-sw sass --parallel --race watch:rollup watch:sass watch:eleventy watch:gulp watch:rollup-sw start


> web.dev@2.0.0 clean C:\Users\rreverser\Downloads\web.dev
> rm -rf dist

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web.dev@2.0.0 clean: `rm -rf dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web.dev@2.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This is because `clean` script relies on Unix command `rm`.

I've tried replacing it with `rimraf` cross-platform command, and then the clean step succeeded, but running into new issues.

For example, building node-sass seems to fail, although I do have `python` on the path (but it searches for `python2`), and it also complains about some 404 error for bindings:

```
> node-sass@4.12.0 install C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.7.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\rreverser\Downloads\web.dev\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\rreverser\Downloads\web.dev\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\rreverser\Downloads\web.dev\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\rreverser\Downloads\web.dev\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\rreverser\Downloads\web.dev\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.7.0
gyp verb command install [ '14.7.0' ]
gyp verb install input version string "14.7.0"
gyp verb install installing version: 14.7.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.7.0
gyp verb build dir attempting to create "build" dir: C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2019',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\rreverser\\.node-gyp\\14.7.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\rreverser\\.node-gyp\\14.7.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\rreverser\\.node-gyp\\14.7.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2019'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\rreverser\Downloads\web.dev\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rreverser\\Downloads\\web.dev\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\rreverser\Downloads\web.dev\node_modules\node-sass
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```

Then, running `npm run dev` starts a server but builds only some artifacts but not others:

```
> npm run dev

> web.dev@2.0.0 dev C:\Users\rreverser\Downloads\web.dev
> npm-run-all clean rollup rollup-sw sass --parallel --race watch:rollup watch:sass watch:eleventy watch:gulp watch:rollup-sw start


> web.dev@2.0.0 clean C:\Users\rreverser\Downloads\web.dev
> rimraf dist


> web.dev@2.0.0 rollup C:\Users\rreverser\Downloads\web.dev
> node build.js

Circular dependency: src\lib\actions.js -> src\lib\fb.js -> src\lib\actions.js
[17:04:42] Finished JS! (bootstrap.js?v=34dce802)
[17:04:42] Generated 10 files

> web.dev@2.0.0 rollup-sw C:\Users\rreverser\Downloads\web.dev
> node build-sw.js

[17:04:49] Build the Service Worker

> web.dev@2.0.0 sass C:\Users\rreverser\Downloads\web.dev
> node ./compile-css.js

[17:04:51] Compiling src/styles/all.scss
[17:04:54] Finished CSS! (app.css?v=ec7a0b54)

> web.dev@2.0.0 watch:rollup C:\Users\rreverser\Downloads\web.dev
> chokidar "src/lib/**/*.{js,scss}" -c --silent "npm run rollup"


> web.dev@2.0.0 watch:sass C:\Users\rreverser\Downloads\web.dev
> chokidar "src/styles/**/*.scss" -c --silent "npm run sass"


> web.dev@2.0.0 watch:eleventy C:\Users\rreverser\Downloads\web.dev
> eleventy --watch --quiet


> web.dev@2.0.0 watch:gulp C:\Users\rreverser\Downloads\web.dev
> npx gulp build --silent && gulp watch --silent


> web.dev@2.0.0 start C:\Users\rreverser\Downloads\web.dev
> node ./server.js


> web.dev@2.0.0 watch:rollup-sw C:\Users\rreverser\Downloads\web.dev
> chokidar "src/lib/**/*.js" -c --silent "npm run rollup-sw"

The server is listening on port 8080
Eleventy is building, please wait…
Wrote 0 files in 0.28 seconds (v0.11.0)
Watching…
```

And then trying to open `localhost:8080` in browser reports:

```
Error: ENOENT: no such file or directory, stat '...\web.dev\dist\en\404\index.html'
```

Finally, trying to change any of the Markdown files doesn't trigger rebuild.

**Expected behavior**

Everything works just like on Unix, the initial website is built, the files are watched and rebuilt and the server is spinning. Many developers use Windows as their primary machine, and it would be great to make it easier for them to contribute to the repo as well.

**Comment by RReverser** [comment]
I'd probably also mention that I tried WSL as an alternative, and that generally proceeded better (although I don't think having access to WSL should be a requirement, as many workplaces prohibit using any VMs), but even then watching files still doesn't work for some reason, requiring manual rebuilds on each change.

**Comment by robdodson** [comment]
- Switching to rimraf or similar module sound good.
- I think we should drop node-sass in favor of canonical dart sass. I was the one asking to keep node-sass because it rebuilds faster but it's not worth headaches for folks.
- For building the markdown files we're using `eleventy --watch` so if that's not working i'm not sure what to do...

**Comment by RReverser** [comment]
>     * For building the markdown files we're using `eleventy --watch` so if that's not working i'm not sure what to do...

I think the problem with this one is rather most likely delimiters in path patterns or some regexes in the config where they expect `/` but not `\`. At least that's my impression from

```
Eleventy is building, please wait…
Wrote 0 files in 0.28 seconds (v0.11.0)
```

and the fact that most assets aren't built in the output folder.

Most likely just requires someone more familiar with Eleventy than me to try and play with paths in configs on a Windows machine.

**Comment by RReverser** [comment]
Definitely not stale...

**Comment by MichaelSolati** [comment]
We just landed a fix that we believe should fix this windows issue. Could you please pull the latest from the `main` branch, run `npm ci` then run `npm run dev` and let us know if the site builds for you!
